name: Deploy Frontend To Azure Server Albatroz Staging

on:
  push:
    branches:
      - main
    paths:
      - "frontend_code/**"
      - ".github/workflows/stage-frontend-deploy.yml"

env:
  KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
  ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
  IMAGE_NAME: dns-manage-frontend
  CONTAINER_NAME: frontend-container
  CONTAINER_PORT: 81
  NAMESPACE: dns-manage
  DEPLOYMENT_NAME: frontend-deployment
  SUCCESS_MESSAGE: "start worker processes"
jobs:
  push:
    name: 📤 Step 2:- Push to Azure ACR
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.set_tag.outputs.image_tag }}

    steps:
      - name: Checkout Code with Full History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Login to Azure Container Registry
        run: |
          docker login ${{ env.ACR_LOGIN_SERVER }} --username ${{ env.ACR_USERNAME }} --password ${{ env.ACR_PASSWORD }}

      - name: Set image tag
        id: set_tag
        run: |
          echo "image_tag=${{ github.sha }}" >> $GITHUB_OUTPUT

      #####################################################################
      # Build Final Image
      #####################################################################

      - name: Build Final frontend Image
        run: |
          docker build \
            -t "${{ env.IMAGE_NAME }}" \
            -f frontend_code/Dockerfile .

      - name: Tag Images
        run: |
          docker tag \
            "${{ env.IMAGE_NAME }}" \
            "${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.image_tag }}"

          docker tag \
            "${{ env.IMAGE_NAME }}" \
            "${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest"

      - name: Push Images
        run: |
          docker push \
            "${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.set_tag.outputs.image_tag }}"

          docker push \
            "${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:latest"

      - name: Remove creds
        run: rm -rvf ~/.kube/config

  deploy:
    name: 🚀 Step 3:- Smoke Test & Deploy on AKS
    runs-on: ubuntu-latest

    needs: push

    env:
      IMAGE_TAG: ${{ needs.push.outputs.image_tag }}

    steps:
      #####################################################################
      # Kubectl
      #####################################################################

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl get nodes

      #####################################################################
      # Create ACR Secret
      #####################################################################

      - name: Create ACR Pull Secret
        run: |
          kubectl create secret docker-registry acr-secret \
            --docker-server="$ACR_LOGIN_SERVER" \
            --docker-username="$ACR_USERNAME" \
            --docker-password="$ACR_PASSWORD" \
            -n "$NAMESPACE" \
            --dry-run=client -o yaml | kubectl apply -f -

      #####################################################################
      # Smoke Test
      #####################################################################

      - name: Smoke Test New Image
        run: |

          TEMP_POD="frontend-smoke-${{ github.run_id }}"
          IMAGE="${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"

          echo "Starting temporary pod..."

          cat <<EOF | kubectl apply -f -
          apiVersion: v1
          kind: Pod
          metadata:
            name: ${TEMP_POD}
            namespace: ${NAMESPACE}
          spec:
            restartPolicy: Never

            nodeSelector:
              kubernetes.azure.com/agentpool: systempool

            imagePullSecrets:
              - name: acr-secret

            containers:
              - name: ${CONTAINER_NAME}
                image: ${IMAGE}

                imagePullPolicy: Always

                ports:
                  - containerPort: ${CONTAINER_PORT}

                envFrom:
                  - secretRef:
                      name: backend-secret
          EOF

          echo "Waiting for pod..."
          kubectl wait \
            --for=condition=Ready \
            pod/${TEMP_POD} \
            -n ${NAMESPACE} \
            --timeout=120s

          echo ""
          echo "Waiting 30 seconds for frontend startup..."
          sleep 30

          echo ""
          echo "Checking application logs..."

          kubectl logs ${TEMP_POD} -n ${NAMESPACE} > logs.txt 2>&1 || true

          echo "================ Logs ================"
          cat logs.txt
          echo "======================================"

          if grep -qF "$SUCCESS_MESSAGE" logs.txt; then

            echo ""
            echo "Database connection successful."
            echo ""

            kubectl delete pod ${TEMP_POD} \
              -n ${NAMESPACE} \
              --ignore-not-found=true

          else

            echo ""
            echo "Database connection failed."
            echo ""

            echo "Pod Status"
            kubectl get pod ${TEMP_POD} -n ${NAMESPACE} -o wide || true

            echo ""
            echo "Describe Pod"
            kubectl describe pod ${TEMP_POD} -n ${NAMESPACE} || true

            echo ""
            echo "Events"
            kubectl get events \
              -n ${NAMESPACE} \
              --sort-by=.lastTimestamp | tail -30 || true

            kubectl delete pod ${TEMP_POD} \
              -n ${NAMESPACE} \
              --ignore-not-found=true

            exit 1

          fi

      #####################################################################
      # Deploy
      #####################################################################

      - name: Update Deployment Image
        run: |

          IMAGE="${ACR_LOGIN_SERVER}/${IMAGE_NAME}:${IMAGE_TAG}"

          kubectl set image \
            deployment/${DEPLOYMENT_NAME} \
            ${CONTAINER_NAME}=${IMAGE} \
            -n ${NAMESPACE}

      - name: Wait for Rollout
        run: |
          kubectl rollout status \
            deployment/${DEPLOYMENT_NAME} \
            -n ${NAMESPACE} \
            --timeout=300s

      #####################################################################
      # Rollback
      #####################################################################

      - name: Rollback if Failed
        if: failure()
        run: |
          echo "Deployment failed. Rolling back..."
          kubectl rollout undo deployment/${DEPLOYMENT_NAME} -n ${NAMESPACE} || true

      #####################################################################
      # Cleanup
      #####################################################################

      - name: Cleanup kubeconfig
        if: always()
        run: |
          rm -rf ~/.kube
